// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as TodosTable } from './Todos';
import type { default as KyselyMigrationLockTable } from './KyselyMigrationLock';
import type { default as KyselyMigrationTable } from './KyselyMigration';

export default interface PublicSchema {
  todos: TodosTable;

  kysely_migration_lock: KyselyMigrationLockTable;

  kysely_migration: KyselyMigrationTable;
}
