// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.rank_minmax */
export type RankMinmaxId = string & { __brand: 'RankMinmaxId' };

/** Represents the table public.rank_minmax */
export default interface RankMinmaxTable {
  id: ColumnType<RankMinmaxId, RankMinmaxId | undefined, RankMinmaxId>;

  min: ColumnType<number, number, number>;

  max: ColumnType<number, number, number>;
}

export type RankMinmax = Selectable<RankMinmaxTable>;

export type NewRankMinmax = Insertable<RankMinmaxTable>;

export type RankMinmaxUpdate = Updateable<RankMinmaxTable>;
