// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.todos */
export type TodosId = string & { __brand: 'TodosId' };

/** Represents the table public.todos */
export default interface TodosTable {
  id: ColumnType<TodosId, TodosId | undefined, TodosId>;

  title: ColumnType<string, string, string>;

  completed: ColumnType<boolean, boolean | undefined, boolean>;

  created_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  updated_at: ColumnType<Date | null, Date | string | null, Date | string | null>;
}

export type Todos = Selectable<TodosTable>;

export type NewTodos = Insertable<TodosTable>;

export type TodosUpdate = Updateable<TodosTable>;
